### ISSUE TITLE
server.shell commands queued but not executed

### ISSUE THREAD

**Issue by romanchyla** [Fizzadar/pyinfra#561] opened 2021-03-27 21:37 UTC
## Describe the bug
`server.shell` operation queued, but never executed

Yes, super weird - and I suspect 'me' is the problem, but earnest effort to find it failed - I can see that the `server.shell` calls are being hashed with the same hash (OK - but even i I put random strings into the name; it still happens; and so I placed one server.shell call at the very beginning; still the same)

I'm not sure where/how the hash is stored - if any; to clear it

I put the logging statements before/after to show the effect; see below the pairs 'checking - finished'

## To Reproduce
Steps to reproduce the behavior (include code & usage example):

code:

```python

"""
Installs and configures prometheus exporter on the device
"""

from pyinfra.operations import server, files
from pyinfra import host, logger
from openwrt import StateGet, StateSet,SystemStateGet, OpkgInstalled

is_dirty = 0

# this should work, but doesn't
logger.info('starting')
pkg = 'prometheus-node-exporter-lua'
server.shell(
    name="Installing: {}".format(pkg),
    commands=["echo 'installing {}'".format(pkg), 'opkg install {}'.format(pkg)]
)

# this was the original block (simplified)
if not host.fact.state_get('system', 'prometheusinstalled') == '2019.11.17-1':
    opkg_updated = False
    for pkg in ["prometheus-node-exporter-lua",
                "prometheus-node-exporter-lua-nat_traffic",
                #"prometheus-node-exporter-lua-netstat",
                #"prometheus-node-exporter-lua-openwrt",
                "prometheus-node-exporter-lua-wifi",
                "prometheus-node-exporter-lua-wifi_stations"]:
        logger.info('Checking package: {}'.format(pkg))
        server.shell(
            name="Installing: {}".format(pkg),
            commands=["echo 'installing {}'".format(pkg), 'opkg install {}'.format(pkg)]
        )
        logger.info('Finished package: {}'.format(pkg))

```

```python
from pyinfra.api import FactBase
from pyinfra import logger

class OpkgInstalled(FactBase):
    '''
    Returns a boolean indicating whether a package is installed
    '''

    def command(self, name):
        self.name = name
        cmd = 'opkg list-installed | grep {} || true'.format(name)
        logger.debug(cmd)
        return cmd

    def process(self, output):
        logger.debug(output)
        for l in output:
            if not l.strip():
                continue
            pkg, version = l.strip().split(' - ')
            if pkg == self.name:
                return True
        return False
```

output of: 

```pyinfra --user root nodes/openwrt.py openwrt/prometheus.py --limit main_router -vvv --debug```

```
(venv) rchyla@tp1:/dvt/workspace/projects/it/confmgmt$ pyinfra --user root nodes/openwrt.py openwrt/prometheus.py --limit main_router -vvv --debug
    [pyinfra_cli.main] Checking potential directory: openwrt
    [pyinfra_cli.main] Checking potential directory: 
    [pyinfra_cli.main] Setting directory to: 
--> Loading config...
--> Loading inventory...
    [pyinfra_cli.inventory] Creating fake inventory...
    [pyinfra_cli.inventory] Looking for group data in: group_data/openwrt.py
    [pyinfra_cli.inventory] Looking for group data in: group_data/__init__.py
    [pyinfra_cli.inventory] Looking for group data in: group_data/devenv.py
    [pyinfra_cli.inventory] Looking for group data in: group_data/all.py

--> Connecting to hosts...
    [pyinfra.api.connectors.ssh] Connecting to: 192.168.3.1 ({'allow_agent': True, 'look_for_keys': True, 'hostname': '192.168.3.1', 'username': 'root', 'timeout': 10})
    [192.168.3.1] Connected
    [pyinfra.api.state] Activating host: 192.168.3.1

--> Preparing operations...
    Loading: openwrt/prometheus.py
    starting
    [pyinfra.api.operation] Adding operation, {'Installing: prometheus-node-exporter-lua'}, opOrder=(15,), opHash=a2db5ca42f2189b4ea48e92035d86e01956e31a7
    [pyinfra.api.facts] Getting fact: state_get (name=system, key=prometheusinstalled) (ensure_hosts: (Host(192.168.3.1),))
    [pyinfra.api.connectors.ssh] Running command on 192.168.3.1: (pty=False) sh -c 'uci -q -c /etc/state show system.prometheusinstalled || true'
[192.168.3.1] >>> sh -c 'uci -q -c /etc/state show system.prometheusinstalled || true'
    [pyinfra.api.connectors.ssh] Waiting for exit status...
    [pyinfra.api.connectors.ssh] Command exit status: 0
    Loaded fact state_get (name=system, key=prometheusinstalled)
    Checking package: prometheus-node-exporter-lua
    [pyinfra.api.operation] Adding operation, {'Installing: prometheus-node-exporter-lua'}, opOrder=(30,), opHash=8f51ac95c49a53bd3a9a50cd83c2951b0a38dcd3
    Finished package: prometheus-node-exporter-lua
    Checking package: prometheus-node-exporter-lua-nat_traffic
    [pyinfra.api.operation] Duplicate hash (8f51ac95c49a53bd3a9a50cd83c2951b0a38dcd3) detected!
    [pyinfra.api.operation] Adding operation, {'Installing: prometheus-node-exporter-lua-nat_traffic'}, opOrder=(30, 1), opHash=8f51ac95c49a53bd3a9a50cd83c2951b0a38dcd3-0
    Finished package: prometheus-node-exporter-lua-nat_traffic
    Checking package: prometheus-node-exporter-lua-wifi
    [pyinfra.api.operation] Duplicate hash (8f51ac95c49a53bd3a9a50cd83c2951b0a38dcd3) detected!
    [pyinfra.api.operation] Duplicate hash (8f51ac95c49a53bd3a9a50cd83c2951b0a38dcd3-0) detected!
    [pyinfra.api.operation] Adding operation, {'Installing: prometheus-node-exporter-lua-wifi'}, opOrder=(30, 2), opHash=8f51ac95c49a53bd3a9a50cd83c2951b0a38dcd3-0-1
    Finished package: prometheus-node-exporter-lua-wifi
    Checking package: prometheus-node-exporter-lua-wifi_stations
    [pyinfra.api.operation] Duplicate hash (8f51ac95c49a53bd3a9a50cd83c2951b0a38dcd3) detected!
    [pyinfra.api.operation] Duplicate hash (8f51ac95c49a53bd3a9a50cd83c2951b0a38dcd3-0) detected!
    [pyinfra.api.operation] Duplicate hash (8f51ac95c49a53bd3a9a50cd83c2951b0a38dcd3-0-1) detected!
    [pyinfra.api.operation] Adding operation, {'Installing: prometheus-node-exporter-lua-wifi_stations'}, opOrder=(30, 3), opHash=8f51ac95c49a53bd3a9a50cd83c2951b0a38dcd3-0-1-2
    Finished package: prometheus-node-exporter-lua-wifi_stations
    [pyinfra.api.facts] Getting fact: state_set (name=system, key=prometheusinstalled, value=2019.11.17-1) (ensure_hosts: (Host(192.168.3.1),))
    [pyinfra.api.connectors.ssh] Running command on 192.168.3.1: (pty=False) sh -c 'uci -q -c /etc/state set system.prometheusinstalled=2019.11.17-1; uci -q -c /etc/state commit system'
[192.168.3.1] >>> sh -c 'uci -q -c /etc/state set system.prometheusinstalled=2019.11.17-1; uci -q -c /etc/state commit system'

```

## Expected behavior
server.shell() commands should be executed

## Meta
+ Include output of `pyinfra --support`.
```
pyinfra --support
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Linux
      Platform: Linux-5.4.0-67-generic-x86_64-with-Ubuntu-18.04-bionic
      Release: 5.4.0-67-generic
      Machine: x86_64
    pyinfra: v1.3.9
    Executable: /dvt/workspace/projects/it/venv/bin/pyinfra
    Python: 3.6.9 (CPython, GCC 8.4.0)
```

**Comment by Fizzadar** [comment] 2021-03-28 16:57
Hi @romanchyla! I'm not following what the issue is here - I can see 5 added operations as expected in the logs?

The hashes are based on the line numbers (`opOrder` in the logs), which is designed such that operations execute "as expected" from the users perspective.

**Comment by Fizzadar** [comment] 2021-04-20 15:38
I'm going to close this issue as I can't see any issues in the log - if more information comes up please send it over (just comment here and/or email me) and I'll re-open the issue to investigate!

**Closed by Fizzadar** 2021-04-20 15:38 UTC
Labels: Bug
