### ISSUE TITLE
Rename the argument name `state` to `name`?

### ISSUE THREAD

**Issue by iredmail** [Fizzadar/pyinfra#340] opened 2020-06-25 06:10 UTC
1. How about rename `state` to `name` (used by Ansible) (or other name) which is easier to understand at first glance?
1. Why not always specify the argument name(s) in each operation in documentation?

e.g. From:

```
apt.packages(
    {'Install iftop'},
    ...
)

server.shell(
    {'Execute hello world script'},
    ...
)
```

To:
```
apt.packages(
    name='Install iftop'
    ...
)

server.shell(
    name='Execute hello world script',
    ...
)
```

**Comment by Fizzadar** [comment] 2020-06-26 12:20
The issue here is some/many operations work nicely with position arguments, ie:

```py
files.put(
    source_file,
    remote_file,
    user='ubuntu',
)
```

So the `set` object as the first argument was chosen as it avoids clashes with other arguments. The naming is entirely optional so we have to be able to support both above format and named:

```py
files.put(
    {'Upload source_file to remote_file'},
    source_file,
    remote_file,
    user='ubuntu',
)
```

Personally, I like the flexibility this allows, but I'd be keen to hear more peoples thoughts on the subject. One option could be to additionally support a global `operation_name` keyword argument (`name` is heavily used as an argument already).

**Comment by iredmail** [comment] 2020-06-29 21:29
It’s recommended to “copy” Andible’s argument names which are short but still clear.  for example:

- replace “source_file” by “etc”
- replace “remote_file” by “path” or “dest”

**Comment by meantheory** [comment] 2020-06-30 19:58
I've stubbed my toe on this state/name thing in that if you forget to wrap this value in the braces, the errors one gets down stream of this are less than helpful or clear as to the root cause. I've tripped over it enough now while playing with things to know to check for it. Haven't actually looked at code enough to know whether changing it is a good or bad idea, just that it is a source of confusion for someone picking up the project for the first time (like me).

**Comment by Fizzadar** [comment] 2020-07-01 09:06
@meantheory absolutely makes sense, this is definitely a bit of a gotcha. I'm keen to improve/remove this.

Given the above, I'm leaning towards a global `name` argument and shortened positional arguments (thanks @iredmail!), such that they can all be provided as keywords; eg:

```py
apk.packages(
    name='Install Asterisk and Vim',
    packages=['asterisk', 'vim'],
    update=True,
)

files.line(
    name='Ensure /netboot/nfs is in /etc/exports',
    path='/etc/exports',
    line=r'/netboot/nfs .*',
    replace='/netboot/nfs *(ro,sync,no_wdelay,insecure_locks,no_root_squash,'
    'insecure,no_subtree_check)',
)
```

This also has the advantage of making all arguments explicit. This will be a breaking change so perfect for v1, will need to maintain backwards compatibility with the set-first-argument still. Will need:

+ Add global `name` argument to set operation name (check for `set` first argument if no `name`)
+ Rename any `name` positional arguments in operations (mostly `files.*`, can be renamed `path` in most cases)
+ Update all examples to use the `name=` keyword syntax (and keywords for all arguments)

**Comment by iredmail** [comment] 2020-07-01 09:49
Didn't realized while typing on phone, it replaced `src` by `etc` in my 2nd reply. Oops.

I personal prefer each operation requires explicit argument names to make it readable, this is same as Ansible. Sometimes you may feel too verbose, but it's easy to understand and maintain.

**Comment by Fizzadar** [comment] 2020-07-01 09:55
@iredmail nw! Agreed explicit > implicit every time.

It has also occurred to me that pyinfra already handles automatic naming where none is provided. So I'm now thinking - add the `name` argument as above, then simply remove the set objects from all the examples, and document the _optional_ `name` argument.

**Comment by Fizzadar** [comment] 2020-07-09 16:33
v1 is merged, will be released after a short pre-release period!

**Closed by Fizzadar** 2020-07-09 16:33 UTC
Labels: Discussion, Operations
