### ISSUE TITLE
ssh host key verification

### ISSUE THREAD

**Issue by themanifold** [Fizzadar/pyinfra#671] opened 2021-09-30 07:31 UTC
Trying to access a server via the pyinfra `ssh` operator that you have never visited before leads to pyinfra hanging because the ssh host key needs to be added on client side. 

Workaround: add the ssh host key manually once before using pyinfra.

**Comment by Fizzadar** [comment] 2021-10-03 15:02
I'm not sure what's going on here - at first I couldn't replicate this so I was looking at the SSH connector and noticed that it's never even loading the system host keys (fixed in https://github.com/Fizzadar/pyinfra/commit/ca73172f9fe82a56807ffbf1b169fa818282d133)! How that means when you add them it fixes the issue is even more confusing. Additionally, the missing host key policy was not setup correctly, fixed in https://github.com/Fizzadar/pyinfra/commit/be6b97c4f6f443227a3fa170d5622fae51e9331b, which should now show a warning when connecting to a host with no matching known hosts entry.

I have just released both fixes in `v1.4.16`. Still confused on why it would hang for you; which paramiko version have you installed?  Thinking it could be some weird interaction between paramiko and the incorrect use of missing key policy?

**Comment by paolodina** [comment] 2021-10-05 00:36
I have the same problem and the workaround doesn't work.

Initially I was on `v1.4.15` and when realized that I did an upgrade to `v1.4.16` but the I still get this error:

```
...
--> Beginning operation run...
--> Starting operation: Install pipx 
[inventories/localhost.py] >>> sh -c 'ssh -p 22 paolo@localhost uptime'
[inventories/localhost.py] Host key verification failed.
    [inventories/localhost.py] Error
--> pyinfra error: No hosts remaining!
```
Btw, manually run the command `sh -c 'ssh -p 22 paolo@localhost uptime` worked as expected.

`paramiko==2.7.2`

**Comment by Fizzadar** [comment] 2021-10-06 16:41
@paolodina does this error persist if you try removing the host key (`ssh-keygen -R localhost`)?

Also - is this actually sshd running on localhost? Not sure but that possibly has issues with host keys (need to research). If so you could use the `@local` connector to execute on the local machine.

**Comment by paolodina** [comment] 2021-10-06 22:35
I tried to remove the host key, no luck again. I think I'm using `pyinfra` incorrectly and I'll open another issue. @Fizzadar thanks for listening.

**Closed as completed** 2021-10-30 18:21 UTC
Labels: bug
